from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH

doc = Document()

# Title
title = doc.add_heading('INT303: Networking Fundamentals', 0)
title.alignment = WD_ALIGN_PARAGRAPH.CENTER

subtitle = doc.add_heading('Lab 2: Exploring Network Interfaces and Packet Transmission', 1)
subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER

# Student Info
doc.add_paragraph('Student: Damian Patrick Ozimede')
doc.add_paragraph('Course: INT303 — Networking Fundamentals')
doc.add_paragraph('Lab: Lab 2')
doc.add_paragraph('Date: June 2026')

doc.add_paragraph('')

# Exercise 1
doc.add_heading('Exercise 1: Viewing and Configuring Network Interfaces', 2)
doc.add_heading('Commands Used:', 3)
doc.add_paragraph('ifconfig\nip addr show')

doc.add_heading('Question 1: What network interfaces are available on your system?', 3)
doc.add_paragraph('Two network interfaces are available on the Kali machine:\n\neth0 — This is the primary Ethernet network interface. It is the main interface used for communication with the local network and the OWASP VM. It is currently active and running as shown by the flags BROADCAST, MULTICAST, UP, LOWER_UP.\n\nlo — This is the loopback interface. It is a virtual interface used by the system to communicate with itself. It is always present on any Linux system and is identified by the flags LOOPBACK, UP, RUNNING.')

doc.add_heading('Question 2: Identify the IP address assigned to each interface.', 3)
doc.add_paragraph('From the ifconfig and ip addr show output, the following IP addresses were identified:\n\neth0:\nIPv4 Address: 192.168.5.139\nSubnet Mask: 255.255.255.0\nBroadcast Address: 192.168.5.255\nIPv6 Address: fe80::20c:29ff:fedb:e853/64\nMAC Address: 00:0c:29:db:e8:53\nMTU: 1500\n\nlo (Loopback):\nIPv4 Address: 127.0.0.1\nSubnet Mask: 255.0.0.0\nIPv6 Address: ::1/128\nMTU: 65536')

doc.add_heading('Question 3: Describe the difference between a loopback interface and an external network interface.', 3)
doc.add_paragraph('A loopback interface (lo) is a virtual software-only interface that allows the system to send and receive network traffic to and from itself. It is not connected to any physical hardware and cannot communicate with any external devices or networks. Its IP address is always 127.0.0.1 and it is commonly used for testing network applications locally, running local services, and internal system communication. Any packet sent to 127.0.0.1 never leaves the machine — it loops straight back to the sender, hence the name loopback.\n\nAn external network interface (eth0) on the other hand is a physical or virtual interface connected to an actual network. It has a real IP address assigned by DHCP (in this case 192.168.5.139) and a MAC address (00:0c:29:db:e8:53) that identifies it on the network. It is responsible for sending and receiving packets to and from other devices on the network, such as the OWASP VM at 192.168.5.130 and the gateway at 192.168.5.254. Without this interface, the Kali machine would have no way of communicating with any external device.\n\nThe key difference is that lo is internal and self-contained while eth0 is external and connects the machine to the wider network.')

doc.add_paragraph('')

# Exercise 2
doc.add_heading('Exercise 2: Capturing Packets on a Specific Interface', 2)
doc.add_heading('Command Used:', 3)
doc.add_paragraph('sudo tcpdump -i eth0 -c 100')

doc.add_heading('Question 1: What kind of packets are being captured?', 3)
doc.add_paragraph('The tcpdump capture on interface eth0 recorded 74 packets and revealed several different types of network traffic:\n\nARP (Address Resolution Protocol) Packets — Multiple ARP requests and replies were captured throughout the session. These included the Kali machine asking "who has 192.168.5.130?" and receiving the reply with the MAC address 00:0c:29:59:23:dd, as well as ARP requests for the gateway at 192.168.5.2. ARP operates at the Data Link Layer and is essential for resolving IP addresses to MAC addresses on the local network.\n\nDNS (Domain Name System) Packets — Several DNS PTR (reverse lookup) queries were captured, where the Kali machine sent requests to 192.168.5.2 asking for hostnames associated with IP addresses. All returned NXDomain responses, meaning no hostname records were found — which is expected in a local lab environment.\n\nUDP Packets — NetBIOS datagram packets were captured from the OWASP VM being broadcast to the network address 192.168.5.255 on the NetBIOS-dgm port. These are Windows networking broadcast packets used for service announcements on the local network.\n\nTCP/HTTP Packets — A full HTTP conversation was captured between the Kali machine and the OWASP VM including the complete TCP three-way handshake, the HTTP GET request, the HTTP 200 OK response with data transfer, and the TCP connection termination using FIN packets.')

doc.add_heading('Question 2: Are there any packets related to communication with the OWASP Broken Web Application VM?', 3)
doc.add_paragraph('Yes, there were several packets directly related to communication with the OWASP VM at 192.168.5.130. The following sequence was clearly visible in the capture:\n\nFirst, an ARP exchange took place where the Kali machine sent a broadcast asking "who has 192.168.5.130?" and the OWASP VM replied with its MAC address 00:0c:29:59:23:dd, establishing the Layer 2 address needed for communication.\n\nThis was immediately followed by the TCP three-way handshake where the Kali machine sent a SYN packet to port 80 on the OWASP VM, the OWASP VM replied with SYN-ACK, and the Kali machine completed the handshake with an ACK.\n\nAfter the handshake, an HTTP GET request was sent from the Kali machine requesting the homepage, and the OWASP VM responded with HTTP/1.1 200 OK, delivering the webpage content in multiple TCP segments.\n\nFinally, a FIN/ACK exchange terminated the connection cleanly after the data transfer was complete.')

doc.add_heading('Question 3: Describe the role of the network interface in transmitting and receiving packets.', 3)
doc.add_paragraph('The network interface eth0 acts as the physical and logical gateway between the Kali machine and the rest of the network. It plays several critical roles in packet transmission and reception:\n\nWhen transmitting, eth0 takes data from the upper layers of the OSI model, encapsulates it into Ethernet frames with the appropriate source MAC address (00:0c:29:db:e8:53), and sends it out onto the network medium towards the destination device.\n\nWhen receiving, eth0 listens for incoming Ethernet frames addressed to its MAC address or broadcast addresses, strips the frame headers, and passes the data up through the network stack to the appropriate protocol handler (IP, TCP, UDP, etc.).\n\nThe interface also handles lower-level functions such as maintaining transmission queues, tracking statistics like bytes sent and received, and managing errors and dropped packets. In this capture, eth0 successfully handled all types of traffic including ARP, DNS, UDP, TCP, and HTTP — demonstrating its central role as the single point through which all network communication flows on the Kali machine.')

doc.add_paragraph('')

# Exercise 3
doc.add_heading('Exercise 3: Examining Network Statistics', 2)
doc.add_heading('Commands Used:', 3)
doc.add_paragraph('netstat -i\nss -s\nss -tuln\nnetstat -an\nnetstat -tn')

doc.add_heading('Question 1: What is the current status of your network interfaces?', 3)
doc.add_paragraph('The netstat -i command displayed the Kernel Interface Table showing the status and statistics of all network interfaces:\n\neth0:\nMTU: 1500\nRX-OK (Packets received successfully): 585,036\nRX-ERR (Receive errors): 0\nRX-DRP (Dropped incoming packets): 0\nTX-OK (Packets transmitted successfully): 234,541\nTX-ERR (Transmit errors): 0\nTX-DRP (Dropped outgoing packets): 402\nFlags: BMRU (Broadcast, Multicast, Running, Up)\n\nlo (Loopback):\nMTU: 65536\nRX-OK: 147,774\nTX-OK: 147,774\nNo errors or drops recorded\nFlags: LRU (Loopback, Running, Up)\n\nBoth interfaces are fully operational with zero receive errors. The 402 dropped TX packets on eth0 are minor and typical in a virtual machine environment. The loopback interface shows perfectly symmetrical RX and TX counts of 147,774 which is expected since all traffic it sends is received by itself.')

doc.add_heading('Question 2: What active connections are visible?', 3)
doc.add_paragraph('The ss -s command showed a summary of all socket statistics:\nTotal sockets: 625\nTCP: 1 socket (0 established, 0 closed, 0 orphaned, 0 timewait)\nUDP: 1 socket\nRAW: 1 socket\nINET: 3 total (2 IPv4, 1 IPv6)\nFRAG: 0\n\nThe ss -tuln command showed one listening TCP port:\ntcp — 127.0.0.1:9050 LISTEN — This is the Tor proxy service running on the loopback interface, waiting for local connections. No other ports were open or listening at the time of the scan.\n\nThe netstat -an command revealed the following active internet connections:\nTCP — 127.0.0.1:9050 LISTEN — Tor proxy listening for connections locally\nUDP — 192.168.5.139:68 to 192.168.5.254:67 ESTABLISHED — Active DHCP communication between the Kali machine (port 68) and the network gateway (port 67), maintaining the IP address lease\nRAW6 — :::58 — An IPv6 raw socket open for ICMPv6 traffic\n\nAdditionally, a large number of UNIX domain sockets were visible, all showing CONNECTED or STREAM states. These are internal communication channels between system processes such as systemd, the X11 display server, D-Bus, and the AT-SPI accessibility bus. These do not represent external network connections.\n\nThe netstat -tn command showed no active established TCP connections at the time of running, confirming that all previous connections to the OWASP VM had already been cleanly terminated.')

doc.add_heading('Question 3: Explain the significance of these statistics in monitoring network performance.', 3)
doc.add_paragraph('Network statistics play a vital role in monitoring and maintaining network performance for several reasons:\n\nError and drop counters — The RX-ERR, RX-DRP, TX-ERR, and TX-DRP values in netstat -i show whether packets are being lost during transmission or reception. Zero receive errors on eth0 confirms the interface is healthy and the network connection is stable.\n\nPacket counters — The RX-OK and TX-OK values show the volume of traffic passing through each interface. eth0 having received over 585,000 packets and transmitted over 234,000 confirms it has been handling significant network activity throughout the lab session.\n\nActive connection monitoring — Tools like ss and netstat -an allow administrators to see exactly what connections are open at any given moment. This is critical for both performance monitoring and security — an unexpected connection to an unknown IP address could indicate a security breach or malware activity.\n\nListening ports — The ss -tuln output shows which ports are open and waiting for connections. In this case only port 9050 (Tor proxy) was listening, confirming no unexpected services were running on the Kali machine.\n\nSocket statistics — The ss -s summary gives a quick overview of the total number of sockets in use, helping identify situations where too many connections are being held open, which could indicate a denial of service attack or a misconfigured application.')

doc.add_paragraph('')

# Exercise 4
doc.add_heading('Exercise 4: Monitoring Network Traffic with Wireshark', 2)
doc.add_heading('Tool Used:', 3)
doc.add_paragraph('Wireshark on interface eth0\nDisplay filter: ip.addr == 192.168.5.130\nTotal packets captured: 98, Dropped: 0 (0.0%)')

doc.add_heading('Wireshark Display Filters Applied:', 3)
doc.add_paragraph('Filter 1 — ip.addr == 192.168.5.130: This filter showed all traffic to and from the OWASP VM. ARP, TCP, and HTTP packets were all visible. The full conversation between the Kali machine and the OWASP VM was displayed including the ARP resolution, TCP handshake, HTTP request and response, and connection termination.\n\nFilter 2 — tcp.port == 80: This filter narrowed the view to only show packets using port 80 (HTTP). 44 out of 98 packets (44.9%) matched this filter. The results showed exclusively the TCP and HTTP communication between 192.168.5.139 and 192.168.5.130, starting from the SYN handshake through to the full HTTP data transfer.\n\nFilter 3 — tcp.port == 443: This filter returned no results — the packet list was completely empty. This means no HTTPS traffic on port 443 was captured during this session. This is expected because the curl command used plain HTTP (port 80) to connect to the OWASP VM, not HTTPS.')

doc.add_heading('Question 1: Analyze the packets going to and from the OWASP VM. What types of protocols are in use?', 3)
doc.add_paragraph('The Wireshark capture recorded 98 packets with 0% packet drop. The following protocols were clearly identified:\n\nARP (Address Resolution Protocol) — Multiple ARP broadcast packets were visible at the beginning of the capture. The most significant was the exchange where the Kali machine asked "Who has 192.168.5.130? Tell 192.168.5.139" and received the reply "192.168.5.130 is at 00:0c:29:59:23:dd". This ARP resolution was necessary before TCP communication could begin.\n\nTCP (Transmission Control Protocol) — The majority of captured packets were TCP packets handling the reliable connection between 192.168.5.139 and 192.168.5.130 on port 80. These included the SYN, SYN-ACK, ACK handshake packets as well as the data transfer ACK packets and final FIN termination packets.\n\nHTTP (HyperText Transfer Protocol) — Packet 18 clearly showed an HTTP GET / HTTP/1.1 request sent from the Kali machine to the OWASP VM. Subsequent packets showed the HTTP response being delivered back in multiple TCP segments.\n\nTLSv1.2 (Transport Layer Security) — Packets 7 and 8 showed TLS traffic between the Kali machine and an external IP address (46.232.250.229), indicating an encrypted HTTPS connection was active in the background during the capture.')

doc.add_heading('Question 2: Can you identify any key packet details such as source/destination IP addresses, port numbers, and flags?', 3)
doc.add_paragraph('Yes, the Wireshark capture provided very detailed packet information:\n\nTCP Three-Way Handshake (Packets 15-17):\nPacket 15 — SYN: Source 192.168.5.139 port 33546 to Destination 192.168.5.130 port 80, Seq=0, Win=64240, MSS=1460, WS=512\nPacket 16 — SYN-ACK: Source 192.168.5.130 port 80 to Destination 192.168.5.139 port 33546, Seq=0, Ack=1, Win=5792, MSS=1460\nPacket 17 — ACK: Source 192.168.5.139 port 33546 to Destination 192.168.5.130 port 80, Seq=1, Ack=1, Win=64512\n\nHTTP Request (Packet 18):\nSource: 192.168.5.139, Destination: 192.168.5.130\nProtocol: HTTP, Length: 143 bytes\nInfo: GET / HTTP/1.1\n\nData Transfer (Packets 20-44):\nMultiple TCP ACK packets carrying 1448 and 2896 bytes of HTTP response data per segment\nTCP PDU reassembly visible — the webpage was broken into multiple segments and reassembled at the destination\n\nPacket Details Panel:\nFrame 15: 74 bytes on wire, 74 bytes captured\nEthernet II: Src VMware_db:e8:53 (00:0c:29:db:e8:53), Dst VMware_59:23:dd (00:0c:29:59:23:dd)\nInternet Protocol Version 4: Src 192.168.5.139, Dst 192.168.5.130\nTransmission Control Protocol: Src Port 33546, Dst Port 80, Seq 0, Len 0')

doc.add_heading('Question 3: How does the TCP/IP model apply to the data captured?', 3)
doc.add_paragraph('The Wireshark capture demonstrates all four layers of the TCP/IP model working together:\n\nLink Layer — corresponds to OSI Layers 1 and 2:\nThe ARP packets and Ethernet II frames operated at this layer. MAC addresses were used to identify and deliver frames between devices on the local network. This was clearly visible in the packet details panel at the bottom of Wireshark.\n\nInternet Layer — corresponds to OSI Layer 3:\nIP addresses (192.168.5.139 and 192.168.5.130) were used for logical addressing and routing of all packets. Every TCP and HTTP packet in the capture carried source and destination IP addresses at this layer.\n\nTransport Layer — corresponds to OSI Layer 4:\nTCP operated at this layer managing the reliable connection. The three-way handshake, data acknowledgements, PSH flags, and FIN flags were all clearly visible. Port numbers (33546 client side, 80 server side) also operate at this layer.\n\nApplication Layer — corresponds to OSI Layers 5, 6 and 7:\nHTTP was the Application layer protocol in use. Packet 18 showed the HTTP GET request and subsequent packets delivered the HTTP 200 OK response. TLSv1.2 was also observed at this layer handling encrypted background HTTPS communication.')

doc.add_paragraph('')

# Exercise 5
doc.add_heading('Exercise 5: Packet Transmission Analysis', 2)
doc.add_heading('Commands Used:', 3)
doc.add_paragraph('sudo tcpdump -i eth0 host 192.168.5.130\nping -c 4 192.168.5.130')

doc.add_heading('Question 1: What do you observe during the packet transmission process?', 3)
doc.add_paragraph('The ping command sent 4 ICMP Echo Request packets to the OWASP VM at 192.168.5.130 and received 4 ICMP Echo Reply packets in return, giving a 0% packet loss. The round trip times recorded were:\nicmp_seq=1 — 0.754 ms\nicmp_seq=2 — 1.23 ms\nicmp_seq=3 — 1.06 ms\nicmp_seq=4 — 1.35 ms\n\nThe minimum round trip time was 0.754 ms, the average was 1.098 ms, and the maximum was 1.351 ms, demonstrating a fast and stable connection between the two machines.\n\nThe tcpdump capture confirmed every step of the transmission in detail. Each ICMP Echo Request from the Kali machine was immediately followed by an ICMP Echo Reply from the OWASP VM, all with the same packet ID of 54143 and sequential sequence numbers 1 through 4. Each packet was 64 bytes in length.\n\nAfter the ping completed, additional network activity was captured including ARP requests, NetBIOS UDP broadcast packets from the OWASP VM, and a DHCP exchange between the OWASP VM and the gateway renewing its IP address lease.')

doc.add_heading('Question 2: Describe the handshake process or the round-trip of the packets for ping.', 3)
doc.add_paragraph('Unlike TCP which uses a three-way handshake, ping uses ICMP which has a simpler two-step round-trip process:\n\nStep 1 — ICMP Echo Request:\nThe Kali machine (192.168.5.139) sent an ICMP Echo Request packet to the OWASP VM (192.168.5.130). This packet contained an identifier (54143) and a sequence number (1, 2, 3, or 4) so the replies could be matched to their requests. The packet was 64 bytes in length and was sent out through the eth0 interface.\n\nStep 2 — ICMP Echo Reply:\nThe OWASP VM received the Echo Request and immediately responded with an ICMP Echo Reply back to the Kali machine. The reply contained the same identifier and sequence number, confirming which request it was responding to. The round-trip time was calculated from the moment the request was sent to the moment the reply was received.\n\nThis two-step process was repeated four times. The tcpdump output clearly showed each request and reply pair in sequence:\n11:42:40 — seq 1 request then reply\n11:42:41 — seq 2 request then reply\n11:42:42 — seq 3 request then reply\n11:42:43 — seq 4 request then reply\n\nEach pair was completed in approximately 1 millisecond, confirming excellent network performance.')

doc.add_heading('Question 3: Which layers of the OSI and TCP/IP models are involved in this transmission?', 3)
doc.add_paragraph('The ping transmission involved multiple layers of both models working together:\n\nOSI Layer 1 — Physical Layer / TCP/IP Link Layer:\nThe raw binary data was transmitted over the virtual Ethernet cable connecting the two machines. The eth0 interface handled the physical transmission.\n\nOSI Layer 2 — Data Link Layer / TCP/IP Link Layer:\nMAC addresses were used to deliver the frames on the local network. The ARP exchange captured by tcpdump was necessary at this layer to encapsulate the ICMP packets into Ethernet frames for local delivery.\n\nOSI Layer 3 — Network Layer / TCP/IP Internet Layer:\nThis is the primary layer where ping operates. ICMP is a Network layer protocol. The IP addresses 192.168.5.139 (source) and 192.168.5.130 (destination) were used at this layer for logical addressing and routing of the ICMP Echo Request and Echo Reply packets.\n\nOSI Layer 4 — Transport Layer / TCP/IP Transport Layer:\nICMP does not use TCP or UDP so it sits directly on top of IP at the Network layer. However the Transport layer was still involved in the background for other traffic visible in the capture such as the DHCP and NetBIOS UDP packets.\n\nOSI Layers 5-7 — Application Layer / TCP/IP Application Layer:\nThe ping utility itself operates as an application that generates and interprets ICMP messages. The application layer handles the formatting of the ICMP messages and the display of round trip time results to the user.')

doc.add_paragraph('')

# Exercise 6
doc.add_heading('Exercise 6: Troubleshooting Network Interface Issues', 2)
doc.add_heading('Commands Used:', 3)
doc.add_paragraph('sudo ifconfig eth0 down\nsudo ifconfig eth0 up')

doc.add_heading('Question 1: What happens when you disable the network interface?', 3)
doc.add_paragraph('When the command sudo ifconfig eth0 down was executed, the eth0 network interface was immediately disabled. The effect was clearly visible in the ping output. Before the interface was brought down, the ping was responding normally with consistent round trip times around 1 ms (icmp_seq=1 through icmp_seq=4).\n\nAs soon as eth0 was disabled, the ping stopped receiving replies completely. The ping continued sending ICMP Echo Request packets but received no responses because the network interface was no longer active. The sequence numbers jumped from icmp_seq=4 all the way to icmp_seq=133 when connectivity was restored, meaning approximately 128 packets were lost during the outage.\n\nThe final ping statistics confirmed the impact: out of 147 packets transmitted, only 19 were received, giving a packet loss rate of 87.0748%. This dramatic packet loss directly reflects the period during which eth0 was disabled.')

doc.add_heading('Question 2: How does your system respond when the interface is re-enabled?', 3)
doc.add_paragraph('When the command sudo ifconfig eth0 up was executed, the eth0 interface was immediately re-enabled and network connectivity was restored. The ping output showed this recovery clearly — from icmp_seq=133 onwards, the OWASP VM began responding again with round trip times back to normal levels around 1-2 ms.\n\nThe recovery was almost instantaneous once the interface was brought back up. The system automatically re-established its network presence on the local network without requiring any manual reconfiguration. The DHCP lease, ARP cache, and routing table were all restored automatically.\n\nThe ping statistics also showed a spike in the maximum round trip time of 30.517 ms (icmp_seq=139 showing 30.5 ms), which occurred immediately after the interface was re-enabled. This is typical behaviour as the network stack needed a brief moment to fully reinitialise before returning to normal performance levels.')

doc.add_heading('Question 3: Explain how network administrators can use this knowledge for troubleshooting connectivity issues.', 3)
doc.add_paragraph('The ability to disable and re-enable network interfaces is a fundamental tool in a network administrator\'s troubleshooting toolkit:\n\nIsolating network faults — When a device is experiencing connectivity problems, an administrator can bring the interface down and back up to reset the network connection. This clears any corrupted state in the network stack and forces the interface to re-negotiate its connection, often resolving intermittent issues without a full system reboot.\n\nForcing DHCP renewal — Bringing an interface down and up again forces the system to release its current IP address and request a fresh DHCP lease. This is useful when a device has been assigned an incorrect or conflicting IP address.\n\nTesting network redundancy — In systems with multiple network interfaces, administrators can disable one interface to test whether the failover to the backup interface works correctly, ensuring critical services remain available even if one network link fails.\n\nSimulating network failures — Administrators use this technique in controlled environments to test how applications and services behave during a network outage, helping them identify and fix weaknesses before a real failure occurs.\n\nClearing ARP cache issues — Bringing the interface down and up again clears the ARP cache and forces fresh ARP resolution, restoring correct communication when devices get stuck communicating with incorrect MAC addresses.')

doc.add_paragraph('')

# Exercise 7
doc.add_heading('Exercise 7: Bandwidth Monitoring', 2)
doc.add_heading('Command Used:', 3)
doc.add_paragraph('sudo iftop -i eth0')

doc.add_heading('Question 1: What is the current bandwidth usage while communicating with the OWASP VM?', 3)
doc.add_paragraph('The iftop display showed the following bandwidth statistics on the eth0 interface:\n\nTransmission (TX):\nCumulative data transmitted: 1.05 KB\nPeak transmission rate: 592b (592 bits per second)\nCurrent rates: 0b, 0b, 30b (2s, 10s, 40s averages)\n\nReception (RX):\nCumulative data received: 28.9 KB\nPeak reception rate: 392b\nCurrent rates: 0b, 0b, 35b\n\nTotal:\nTotal cumulative data transferred: 30.0 KB\nPeak total rate: 896b\nCurrent rates: 0b, 0b, 65b\n\nTwo active connections were visible:\n192.168.5.139 to 192.168.5.2 — The Kali machine communicating with the local gateway\n192.168.5.139 to reserved.vm — The Kali machine communicating with another host on the network\n\nThe significant difference between TX (1.05 KB) and RX (28.9 KB) is completely expected. The Kali machine sent a small HTTP GET request while the OWASP VM responded with the full HTML content of its homepage, which is much larger in size.')

doc.add_heading('Question 2: Identify the impact of network traffic on your interface. Is there any traffic congestion?', 3)
doc.add_paragraph('Based on the iftop output, there was no traffic congestion on the eth0 interface during the communication with the OWASP VM. The bandwidth usage was extremely low compared to the maximum capacity of the interface.\n\nThe eth0 interface has a maximum MTU of 1500 bytes and is capable of handling up to 1000 Mbps on a standard virtual Ethernet connection. The peak total bandwidth recorded was only 896 bits per second (approximately 0.0009 Mbps), which represents a tiny fraction of the available capacity. The total data transferred was just 30.0 KB for the entire session.\n\nThe current rates showing 0b across most columns at the time of the screenshot confirm that the brief HTTP transaction had already completed and the interface had returned to an idle state.')

doc.add_heading('Question 3: How does this help in monitoring network performance?', 3)
doc.add_paragraph('Bandwidth monitoring tools like iftop provide network administrators with valuable real-time insights into network performance:\n\nIdentifying bandwidth hogs — iftop lists all active connections sorted by bandwidth usage, making it immediately obvious which connections or hosts are consuming the most bandwidth.\n\nDetecting unusual traffic patterns — A sudden spike in bandwidth usage could indicate a security incident such as data exfiltration, malware, or a denial of service attack.\n\nCapacity planning — By monitoring peak bandwidth usage over time, administrators can determine whether the current network infrastructure is sufficient or whether upgrades are needed.\n\nVerifying traffic flows — iftop confirmed that the Kali machine was communicating with the gateway and another host on the network, giving administrators a clear picture of exactly which hosts are talking to each other.\n\nTroubleshooting slow connections — If a user reports slow network performance, iftop can immediately show whether the interface is saturated, helping administrators pinpoint whether the problem is local bandwidth congestion or an issue further upstream.')

doc.add_paragraph('')

# Exercise 8
doc.add_heading('Exercise 8: Advanced Packet Capture Filters', 2)
doc.add_heading('Command Used:', 3)
doc.add_paragraph("sudo tcpdump -i eth0 'tcp port 80 and host 192.168.5.130'")

doc.add_heading('Question 1: What is the significance of filtering specific traffic?', 3)
doc.add_paragraph('The custom filter combined two conditions to capture only HTTP traffic specifically between the Kali machine and the OWASP VM. The results were dramatically more focused compared to the unfiltered tcpdump capture in Exercise 2, which captured 74 packets of mixed traffic. This filtered capture returned only 36 packets — all of them directly relevant to the HTTP conversation.\n\nNoise reduction — In a real network environment, hundreds or thousands of packets pass through an interface every second. Without filtering, finding specific traffic would be like searching for a needle in a haystack. Filters immediately eliminate all irrelevant traffic.\n\nPrecision analysis — The filtered capture showed the complete HTTP conversation in clean, readable sequence from the TCP three-way handshake at 21:39:25.126513 all the way through to the final FIN/ACK termination at 21:39:25.217882. Every single packet was directly relevant to the task being analysed.\n\nFaster troubleshooting — When a specific service is experiencing problems, filtering allows an administrator to isolate that exact traffic stream and analyse it without being distracted by unrelated packets.\n\nSecurity investigations — During a security incident, filters help analysts focus on suspicious traffic patterns, allowing them to see exactly what a specific IP address is doing on the network.')

doc.add_heading('Question 2: How can advanced filters help network engineers diagnose and resolve issues?', 3)
doc.add_paragraph('Advanced packet capture filters are one of the most powerful diagnostic tools available to network engineers:\n\nCombining multiple conditions — The filter used the AND operator to combine two conditions — the protocol/port (TCP port 80) and the host IP address (192.168.5.130). This kind of compound filtering allows engineers to be extremely precise about what traffic they capture.\n\nProtocol-specific analysis — By filtering on tcp port 80, the capture exclusively showed HTTP traffic. This allowed clear observation of the complete HTTP session lifecycle including the TCP handshake, HTTP GET request, HTTP 200 OK response, and the clean FIN/ACK connection termination. The entire transaction completed in just 0.091 seconds.\n\nPerformance diagnosis — The captured data clearly showed sequence numbers incrementing with each packet (seq 1:2897, 2897:4345, 4345:7241 etc.), confirming data was being delivered in order with no gaps or retransmissions. Retransmissions would appear as duplicate sequence numbers — a clear sign of network problems.\n\nConnection state tracking — The flags visible in each packet (SYN, SYN-ACK, ACK, PSH, FIN) tell engineers the exact state of the TCP connection at every point. PSH flags indicate the sender was instructing the receiver to pass data immediately to the application layer. FIN flags confirmed a clean connection termination rather than an abrupt reset.\n\nBaseline establishment — By capturing and analysing normal traffic patterns, network engineers establish a baseline of what healthy traffic looks like. When something goes wrong in the future, they can compare suspicious captures against this baseline to identify anomalies.')

# Save
doc.save('/home/legion/Kali-Linux-Security-Labs/INT303/Lab2/INT303_Lab2_Report.docx')
print("Report saved successfully!")
